// Generated by CoffeeScript 1.3.3
(function() {
  var Server;

  Server = (function() {

    function Server(name, host, config, mainConfig) {
      var cron;
      this.name = name;
      this.host = host;
      this.start = config.start || mainConfig.getStart();
      this.install = config.install || mainConfig.getInstall();
      cron = config.cron ? mainConfig.normalizeCron(cron) : null;
      this.cron = cron || mainConfig.getCron();
    }

    Server.prototype.getStart = function() {
      return this.start || (function() {
        throw new Error("You must specify 'start:' in your config file");
      })();
    };

    Server.prototype.getInstall = function() {
      return this.install || (function() {
        throw new Error("You must specify 'install:' in your config file");
      })();
    };

    Server.prototype.getCron = function() {
      return this.cron;
    };

    Server.prototype.getUser = Server.host.replace(/@.*$/, "");

    Server.prototype.getHost = Server.host;

    return Server;

  })();

  module.exports = Server;

}).call(this);
